language: node_js
node_js:
  - 9
  - 8
  - 6

env:
  NPM_TOKEN

deploy:
  - provider: npm
    email: kraihn@gmail.com
    api_key: $NPM_TOKEN
    tag: next
    on:
      branch: next
      node: '9'
  - provider: npm
    email: kraihn@gmail.com
    api_key: $NPM_TOKEN
    on:
      branch: master
